Feature/add docker
khodakhah/nodcms pull request #90
Opened 2022-08-08 18:00 UTC by anvari182

2022-08-24 16:30 UTC, anvari182 commented
I used PHP 8.0 for docker version

2022-08-26 12:02 UTC, khodakhah commented
There is a problem with mysql-server on docker windows.
I'm getting this report in an unlimited loop.
```shell
2022-08-26T11:54:48.477462Z 0 [ERROR] [MY-010119] [Server] Aborting
2022-08-26T11:54:50.197093Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.30)  MySQL Community Server - GPL.
2022-08-26 11:55:52+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2022-08-26 11:55:52+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.30-1.el8 started.
ln: failed to create symbolic link '/var/lib/mysql/mysql.sock': Operation not permitted
2022-08-26T11:55:53.202445Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
2022-08-26T11:55:53.209447Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.30) starting as process 1
2022-08-26T11:55:53.215762Z 0 [Warning] [MY-010159] [Server] Setting lower_case_table_names=2 because file system for /var/lib/mysql/ is case insensitive
2022-08-26T11:55:53.236478Z 0 [Warning] [MY-000054] [Server] World-writable config file '/var/lib/mysql/auto.cnf' is ignored.
2022-08-26T11:55:53.239399Z 0 [Warning] [MY-010107] [Server] World-writable config file '/var/lib/mysql/auto.cnf' has been removed.
2022-08-26T11:55:53.242059Z 0 [Warning] [MY-010075] [Server] No existing UUID has been found, so we assume that this is the first time that this server has been started. Generating a new UUID: 09465322-2536-11ed-b0fb-0242ac130002.
2022-08-26T11:55:53.269243Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2022-08-26T11:55:53.819809Z 1 [ERROR] [MY-012592] [InnoDB] Operating system error number 13 in a file operation.
2022-08-26T11:55:53.820043Z 1 [ERROR] [MY-012595] [InnoDB] The error means mysqld does not have the access rights to the directory.
2022-08-26T11:55:53.820055Z 1 [ERROR] [MY-013902] [InnoDB] Failed to remove unused redo log file ./#innodb_redo/#ib_redo13_tmp.
2022-08-26T11:55:54.858818Z 1 [ERROR] [MY-012592] [InnoDB] Operating system error number 13 in a file operation.
2022-08-26T11:55:54.858926Z 1 [ERROR] [MY-012595] [InnoDB] The error means mysqld does not have the access rights to the directory.
2022-08-26T11:55:54.858948Z 1 [ERROR] [MY-013902] [InnoDB] Failed to remove unused redo log file ./#innodb_redo/#ib_redo13_tmp.
2022-08-26T11:55:56.567859Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
mysqld: Table 'mysql.plugin' doesn't exist
2022-08-26T11:55:56.860237Z 0 [ERROR] [MY-010735] [Server] Could not open the mysql.plugin table. Please perform the MySQL upgrade procedure.
2022-08-26T11:55:56.860418Z 0 [Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
2022-08-26T11:55:56.860546Z 0 [Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
2022-08-26T11:55:56.860696Z 0 [Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
2022-08-26T11:55:56.860916Z 0 [Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
2022-08-26T11:55:56.861041Z 0 [Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
2022-08-26T11:55:56.861171Z 0 [Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
2022-08-26T11:55:56.861288Z 0 [Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
2022-08-26T11:55:57.018045Z 0 [Warning] [MY-010015] [Repl] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
2022-08-26T11:55:57.140397Z 0 [Warning] [MY-010015] [Repl] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
2022-08-26T11:55:57.154702Z 0 [Warning] [MY-013595] [Server] Failed to initialize TLS for channel: mysql_main. See below for the description of exact issue.
2022-08-26T11:55:57.154749Z 0 [Warning] [MY-010069] [Server] Failed to set up SSL because of the following SSL library error: SSL context is not usable without certificate and private key
2022-08-26T11:55:57.163830Z 0 [Warning] [MY-010284] [Server] RSA public key file not found: /var/lib/mysql//public_key.pem. Some authentication plugins will not work.
2022-08-26T11:55:57.169256Z 0 [Warning] [MY-010284] [Server] RSA public key file not found: /var/lib/mysql//public_key.pem. Some authentication plugins will not work.
2022-08-26T11:55:57.172751Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
2022-08-26T11:55:57.173223Z 0 [Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
2022-08-26T11:55:57.173411Z 0 [ERROR] [MY-013129] [Server] A message intended for a client cannot be sent there as no client-session is attached. Therefore, we're sending the information to the error-log instead: MY-001146 - Table 'mysql.component' doesn't exist
2022-08-26T11:55:57.173457Z 0 [Warning] [MY-013129] [Server] A message intended for a client cannot be sent there as no client-session is attached. Therefore, we're sending the information to the error-log instead: MY-003543 - The mysql.component table is missing or has an incorrect definition.
2022-08-26T11:55:57.173872Z 0 [ERROR] [MY-010326] [Server] Fatal error: Can't open and lock privilege tables: Table 'mysql.user' doesn't exist
2022-08-26T11:55:57.173948Z 0 [ERROR] [MY-010952] [Server] The privilege system failed to initialize correctly. For complete instructions on how to upgrade MySQL to a new version please see the 'Upgrading MySQL' section from the MySQL manual.
```

2022-08-26 12:49 UTC, khodakhah requested changes

2022-08-26 12:49 UTC, khodakhah commented on nodcms-core/Validation/Rules.php
> -    public function validateFileExists($value, string $param = "string ", array $data, string &$error = null): bool
This change causes following error:
```json
{
    "title": "TypeError",
    "type": "TypeError",
    "code": 500,
    "message": "Argument 2 passed to NodCMS\\Core\\Validation\\Rules::validateFileExists() must be of the type array, string given, called in /var/www/Repositories/nodcms/vendor/codeigniter4/framework/system/Validation/Validation.php on line 306",
    "file": "/var/www/Repositories/nodcms/nodcms-core/Validation/Rules.php",
    "line": 706
}
```
You could just remove default value of `$param` ore add default value on `$data`.

2022-08-26 12:49 UTC, khodakhah commented on nodcms-installer/Controllers/Installer.php
> +                'class'=>"select2me select2-element",
The CSS class name `select2me` have been used exactly for this feature that you added. Somehow the JS library have been removed.
Please use the `select2me`!

2022-08-26 12:49 UTC, khodakhah commented on CHANGELOG.md
> +- Docker to the project.
Please resolve the duplicate `### Added`.

2022-08-26 12:55 UTC, khodakhah requested changes

2022-08-26 12:55 UTC, khodakhah commented on docker-compose.yml
> +  database:
There is a problem with mysql-server on docker windows.
I'm getting this report in an unlimited loop.
```shell
2022-08-26T11:54:48.477462Z 0 [ERROR] [MY-010119] [Server] Aborting
2022-08-26T11:54:50.197093Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.30)  MySQL Community Server - GPL.
2022-08-26 11:55:52+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2022-08-26 11:55:52+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.30-1.el8 started.
ln: failed to create symbolic link '/var/lib/mysql/mysql.sock': Operation not permitted
2022-08-26T11:55:53.202445Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
2022-08-26T11:55:53.209447Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.30) starting as process 1
2022-08-26T11:55:53.215762Z 0 [Warning] [MY-010159] [Server] Setting lower_case_table_names=2 because file system for /var/lib/mysql/ is case insensitive
2022-08-26T11:55:53.236478Z 0 [Warning] [MY-000054] [Server] World-writable config file '/var/lib/mysql/auto.cnf' is ignored.
2022-08-26T11:55:53.239399Z 0 [Warning] [MY-010107] [Server] World-writable config file '/var/lib/mysql/auto.cnf' has been removed.
2022-08-26T11:55:53.242059Z 0 [Warning] [MY-010075] [Server] No existing UUID has been found, so we assume that this is the first time that this server has been started. Generating a new UUID: 09465322-2536-11ed-b0fb-0242ac130002.
2022-08-26T11:55:53.269243Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2022-08-26T11:55:53.819809Z 1 [ERROR] [MY-012592] [InnoDB] Operating system error number 13 in a file operation.
2022-08-26T11:55:53.820043Z 1 [ERROR] [MY-012595] [InnoDB] The error means mysqld does not have the access rights to the directory.
2022-08-26T11:55:53.820055Z 1 [ERROR] [MY-013902] [InnoDB] Failed to remove unused redo log file ./#innodb_redo/#ib_redo13_tmp.
2022-08-26T11:55:54.858818Z 1 [ERROR] [MY-012592] [InnoDB] Operating system error number 13 in a file operation.
2022-08-26T11:55:54.858926Z 1 [ERROR] [MY-012595] [InnoDB] The error means mysqld does not have the access rights to the directory.
2022-08-26T11:55:54.858948Z 1 [ERROR] [MY-013902] [InnoDB] Failed to remove unused redo log file ./#innodb_redo/#ib_redo13_tmp.
2022-08-26T11:55:56.567859Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
mysqld: Table 'mysql.plugin' doesn't exist
2022-08-26T11:55:56.860237Z 0 [ERROR] [MY-010735] [Server] Could not open the mysql.plugin table. Please perform the MySQL upgrade procedure.
2022-08-26T11:55:56.860418Z 0 [Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
2022-08-26T11:55:56.860546Z 0 [Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
2022-08-26T11:55:56.860696Z 0 [Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
2022-08-26T11:55:56.860916Z 0 [Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
2022-08-26T11:55:56.861041Z 0 [Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
2022-08-26T11:55:56.861171Z 0 [Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
2022-08-26T11:55:56.861288Z 0 [Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
2022-08-26T11:55:57.018045Z 0 [Warning] [MY-010015] [Repl] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
2022-08-26T11:55:57.140397Z 0 [Warning] [MY-010015] [Repl] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
2022-08-26T11:55:57.154702Z 0 [Warning] [MY-013595] [Server] Failed to initialize TLS for channel: mysql_main. See below for the description of exact issue.
2022-08-26T11:55:57.154749Z 0 [Warning] [MY-010069] [Server] Failed to set up SSL because of the following SSL library error: SSL context is not usable without certificate and private key
2022-08-26T11:55:57.163830Z 0 [Warning] [MY-010284] [Server] RSA public key file not found: /var/lib/mysql//public_key.pem. Some authentication plugins will not work.
2022-08-26T11:55:57.169256Z 0 [Warning] [MY-010284] [Server] RSA public key file not found: /var/lib/mysql//public_key.pem. Some authentication plugins will not work.
2022-08-26T11:55:57.172751Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
2022-08-26T11:55:57.173223Z 0 [Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
2022-08-26T11:55:57.173411Z 0 [ERROR] [MY-013129] [Server] A message intended for a client cannot be sent there as no client-session is attached. Therefore, we're sending the information to the error-log instead: MY-001146 - Table 'mysql.component' doesn't exist
2022-08-26T11:55:57.173457Z 0 [Warning] [MY-013129] [Server] A message intended for a client cannot be sent there as no client-session is attached. Therefore, we're sending the information to the error-log instead: MY-003543 - The mysql.component table is missing or has an incorrect definition.
2022-08-26T11:55:57.173872Z 0 [ERROR] [MY-010326] [Server] Fatal error: Can't open and lock privilege tables: Table 'mysql.user' doesn't exist
2022-08-26T11:55:57.173948Z 0 [ERROR] [MY-010952] [Server] The privilege system failed to initialize correctly. For complete instructions on how to upgrade MySQL to a new version please see the 'Upgrading MySQL' section from the MySQL manual.
```

2022-08-30 19:15 UTC, anvari182 commented on nodcms-core/Validation/Rules.php
> -    public function validateFileExists($value, string $param = "string ", array $data, string &$error = null): bool
Done!

2022-08-30 19:16 UTC, anvari182 commented on nodcms-installer/Controllers/Installer.php
> +                'class'=>"select2me select2-element",
Done!

2022-08-30 19:16 UTC, anvari182 commented on CHANGELOG.md
> +- Docker to the project.
Done!

2022-08-30 19:17 UTC, anvari182 commented on docker-compose.yml
> +  database:
I tried it on windows and it worked as expected, please try again.

2022-10-04 18:30 UTC, khodakhah commented on CHANGELOG.md
>  ### Added
Can you please move this change under the [Unreleased] tag?
I thing it has been changed after merging with the master.

2022-10-05 17:27 UTC, anvari182 commented on CHANGELOG.md
>  ### Added
Done

2022-10-06 18:32 UTC, khodakhah approved these changes

2022-10-06 18:33 UTC, merged