Add db variables to env
khodakhah/nodcms pull request #93
Opened 2022-08-21 14:32 UTC by anvari182

Add database variables into env file

2022-08-21 16:48 UTC, khodakhah requested changes
There are an ERROR and some issues/wishes.

2022-08-21 16:48 UTC, khodakhah commented on nodcms-core/Libraries/DatabaseEnvConfig.php
> +    public function writeToEnv()
I think, it's better and more developer friendly 😁 to use fn inputs instead of using __set().
Also, It could be the best solution to solve the ERROR!

2022-08-21 16:48 UTC, khodakhah commented on nodcms-installer/Controllers/Installer.php
> +            foreach ($_SESSION['database_connect'] as $key => $value) {
Could you list your changes in CHANGELOG.md under ``[Unreleased]``? I'll assign the version to them while creating a new tag.

2022-08-21 16:48 UTC, khodakhah commented on nodcms-core/Libraries/DatabaseEnvConfig.php
> +        $this->databaseConfig[$name] = $value;
ERROR:
```json
{
    "title": "Error",
    "type": "Error",
    "code": 500,
    "message": "Typed property NodCMS\\Core\\Libraries\\DatabaseEnvConfig::$databaseConfig must not be accessed before initialization",
    "file": "/var/www/Repositories/nodcms/nodcms-core/Libraries/DatabaseEnvConfig.php",
    "line": 11
}
```
> PHP 7.4.3
> on the last installation step **complete**

2022-08-21 20:06 UTC, anvari182 commented on nodcms-core/Config/Services.php
> +
Done!

2022-08-21 20:06 UTC, anvari182 commented on nodcms-core/Libraries/DatabaseEnvConfig.php
> +
Done!

2022-08-21 20:08 UTC, anvari182 commented on nodcms-installer/Controllers/Installer.php
> +        if (!$this->hasAccess()) {
totally agree :+1:

2022-08-21 20:09 UTC, anvari182 commented on nodcms-core/Libraries/DatabaseEnvConfig.php
> +    public function writeToEnv()
Thank you for the valuable feedback, i refactored the class

2022-08-21 20:10 UTC, anvari182 commented on nodcms-core/Libraries/DatabaseEnvConfig.php
> +        $this->databaseConfig[$name] = $value;
It should be fixed

2022-08-21 20:10 UTC, anvari182 commented
@khodakhah please review it again please

2022-08-23 18:16 UTC, khodakhah approved these changes

2022-08-23 18:16 UTC, merged